application: phyton-angular-gae
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: (.*)/
  static_files: index.html
  upload: index.html

- url: /node_modules/angular/angular.min.js
  static_files: node_modules/angular/angular.min.js
  upload: node_modules/angular

- url: (/.*\.js)
  static_files: js\1
  upload: js

- url: (/.*\.css)
  static_files: listadetareas.css
  upload: listadetareas.css
