application: phyton-angular-gae
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: (.*)/
  static_files: index.html
  upload: index.html

- url: /node_modules/angular/angular.js
  static_files: node_modules/angular/angular.js
  upload: node_modules/angular

- url: /node_modules/angular-route/angular-route.js
  static_files: node_modules/angular-route/angular-route.js
  upload: node_modules/angular-route

- url: (/.*\.js)
  static_files: js\1
  upload: js

- url: (/.*\.css)
  static_files: css\1
  upload: css

- url: (/.*\.woff)
  static_files: css\1
  upload: css

- url: (/.*\.map)
  static_files: css\1
  upload: css
