application: phyton-angular-gae
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: (.*)/
  static_files: index.html
  upload: index.html

- url: (/.*\.js)
  static_files: listadetareas.js
  upload: listadetareas.js

- url: (/.*\.css)
  static_files: listadetareas.css
  upload: listadetareas.css
